FROM node:latest as build

# Set the working directory
WORKDIR /app/web/client

# Build dependencies
COPY ./tsconfig.json /app
COPY ./common /app/common
COPY ./web/client /app/web/client
RUN yarn install
RUN yarn build

# Use custom nginx.conf
FROM nginx:latest
COPY --from=build /app/web/client/dist /usr/share/nginx/html
COPY web/client/.nginx/nginx.conf /etc/nginx/conf.d/default.conf
